### ISSUE TITLE
AssertionError: MMCV==1.6.2 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

### ISSUE THREAD

**Issue by zha11037** [NVlabs/OmniDrive#12]
Thank you for your great work!

I met some problem when I installed mmcv-full.

I followed your documentation step by step, but it went wrong when I installed mmcv-full:
`pip install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html`

Error:
```
RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mmcv-full)
```
To solve this question, I downloaded the wheel document from website and it worked. 

But when I ran the test code, it occoured that:
`AssertionError: MMCV==1.6.2 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.`

I learned that it is hard to change the version of MMCV to 2.0 or above because of the updates in the code.

How can I solve this problem?

**Comment by zha11037** [comment]
Hi! I tried solving the problem, it seemed that there is a version conflict between my mmdetection3d and mmcv.The reason may be thet I haven't successfully run the command `git checkout v1.0.0rc6`. However, I still can't run this command, can you tell me how it change the code of  mmdetection3d?

**Comment by exiawsh** [comment]
You need recompile mmdet3d 1.0.0rc6

**Comment by zha11037** [comment]
> You need recompile mmdet3d 1.0.0rc6

Thank you for your reply! I am trying fixing it.

**Comment by hey-cjj** [comment]
It should be 1.7.2
