### ISSUE TITLE
Meta data of OmiDrive-NuScene

### ISSUE THREAD

**Issue by FanHengbo** [NVlabs/OmniDrive#2]
Really appreciate your work! 

Recently I've downloaded the Omidrive-NuScene dataset, however I couldn't find the meta data that can be used to index original NuScene dataset. I wonder if it is possible to release the details of your dataset, like the structure of it and how to find corresponding image views from NuScene. 

Best Regards.

**Comment by exiawsh** [comment]
Hi,
thanks for you attention!
And we are also considering using gpt4o to regenerate the data in June to improve the quality. Please note that the data may change at that time.
We hope that this part of the data can be helpful in your task, so we have released the recent version in advance.
@FanHengbo The file name of the data is the sample token in nuscens. You can load the data in this way:
sample_idx=info['token'] # ('sample_token' for nusc)
 with open(vqa_path+results['sample_idx']+".json", 'r') as f:
         data_qa = json.load(f)

**Comment by FanHengbo** [comment]
Thanks! This really helps me a lot!
