### ISSUE TITLE
can not download 2D llm weights

### ISSUE THREAD

**Issue by jameskobehoward** [NVlabs/OmniDrive#22]
Hello! I can not download 2D llm weights. Could you put it in github or baidunetpan please?Thank you!

![Image 3](https://github.com/user-attachments/assets/ab844b59-b9dd-41b4-9013-7da87617db18)

**Comment by yuxr-smile** [comment]
请问您解决了吗

**Comment by yuxr-smile** [comment]
The author will share 2D LLM weights with you！

________________________________

**Comment by yuxr-smile** [comment]
I  don't resolve this issue

________________________________
