### ISSUE TITLE
Code Plan

### ISSUE THREAD

**Issue by xiaobh1519** [NVlabs/OmniDrive#3]
Hi～ I noticed you plan to open-source the code on July 1st. Are there any updates or changes?

**Comment by exiawsh** [comment]
I'm having a few more issues supporting deepspeed training, which will be resolved soon. In addition, the code also has an internal approval process. (If the deepspeed training problem is not solved by 7.15, I will also submit the code for approval and release that version)

**Comment by exiawsh** [comment]
I'm sorry. I originally had two plans, one to support deepspeed based on mmdet3d 1.0, but it was difficult. Older versions of mmcv are difficult to support. So I'm still thinking about migrating the code to mmdet3d 1.1+, but there are significant modification and migration costs from the pkl dataset and profiling.

**Comment by xiaobh1519** [comment]
> I'm sorry. I originally had two plans, one to support deepspeed based on mmdet3d 1.0, but it was difficult. Older versions of mmcv are difficult to support. So I'm still thinking about migrating the code to mmdet3d 1.1+, but there are significant modification and migration costs including the pkl dataset and metrics. Sorry again for not being able to open source on time.

OK, Thanks for quick reply!
