### ISSUE TITLE
About the unequal numbers of json files in train split of OmniDrive-nuScenes.

### ISSUE THREAD

**Issue by dszpr** [NVlabs/OmniDrive#4]
Really appreciate for your amazing work!

I tried to generate an annotation file from the json files of OmniDrive-nuScenes, and I found that the numbers of json files in the four train split directories (desc/keywords/planning/conv) seems to be unequal. In fact, the number of json files in planning directory is less than that in other directories, leading to a FileNotFound error when I open json file in the other three directories based on the filename in planning directory.

Please refer to the count below:
Directory: /OmniDrive/omnidrive_data/desc/train, File Count: 28130
Directory: /OmniDrive/omnidrive_data/keywords/train, File Count: 28130
Directory: /OmniDrive/omnidrive_data/planning/train, File Count: 27968
Directory: /OmniDrive/omnidrive_data/conv/train, File Count: 28130

However, the numbers of json files in the four val split directories are equal:
Directory: /OmniDrive/omnidrive_data/desc/val, File Count: 6019
Directory: /OmniDrive/omnidrive_data/keywords/val, File Count: 6019
Directory: /OmniDrive/omnidrive_data/planning/val, File Count: 6019
Directory: /OmniDrive/omnidrive_data/conv/val, File Count: 6019

Could you please explain the reason why the file numbers in train split are not equal?

**Comment by exiawsh** [comment]
Hi. In the nusc  training set, some scenes have incomplete map information. I skipped those samples when generating data.

**Comment by dszpr** [comment]
Got it. Thanks for the quick reply.
