### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by xiaobh1519** [NVlabs/OmniDrive#5]
Hi! Thanks for great work! When will the code release?

**Comment by exiawsh** [comment]
We will open source the Initial version（built upon mmdet1.0 without deepspeed) in two days.
There are still bugs in the mmdet1.1 version that need to be fixed. 
Please note that without deepspeed, A100 is required for training

**Comment by exiawsh** [comment]
update:
will opensource omnidrive (mmdet1.0) tomorrow.
And I fix bugs in mmdet3d (1.4, can use deepspeed to reduce training memory), it can successfully reproduce the detection results of streampetr. I am currently migrating omnidrive. Omnidrive uses OpenLanev2, but the evaluation of OpenLanev2 has not been migrated to mmdet3d (1.4), so centerline prediction will be canceled in this version.

**Comment by xiaobh1519** [comment]
> update: will opensource omnidrive (mmdet1.0) tomorrow. And I fix bugs in mmdet3d (1.4, can use deepspeed to reduce training memory), it can successfully reproduce the detection results of streampetr. I am currently migrating omnidrive. Omnidrive uses OpenLanev2, but the evaluation of OpenLanev2 has not been migrated to mmdet3d (1.4), so centerline prediction will be canceled in this version.

Thanks！！！

**Comment by xiaobh1519** [comment]
> update:
> will opensource omnidrive (mmdet1.0) tomorrow.
> And I fix bugs in mmdet3d (1.4, can use deepspeed to reduce training memory), it can successfully reproduce the detection results of streampetr. I am currently migrating omnidrive. Omnidrive uses OpenLanev2, but the evaluation of OpenLanev2 has not been migrated to mmdet3d (1.4), so centerline prediction will be canceled in this version.

I see that there is no file in the folder, it seems that the upload failed

**Comment by exiawsh** [comment]
2 hours. I'm working with readme and environment setup file.

**Comment by haofuly** [comment]
> update: will opensource omnidrive (mmdet1.0) tomorrow. And I fix bugs in mmdet3d (1.4, can use deepspeed to reduce training memory), it can successfully reproduce the detection results of streampetr. I am currently migrating omnidrive. Omnidrive uses OpenLanev2, but the evaluation of OpenLanev2 has not been migrated to mmdet3d (1.4), so centerline prediction will be canceled in this version.

Hi, thanks for opening source quickly.
Does this repo support the original StreamPETR pipeline for 3D detection, or I must use the official StreamPETR repo? If support, can you give the config file?

**Comment by exiawsh** [comment]
> > update: will opensource omnidrive (mmdet1.0) tomorrow. And I fix bugs in mmdet3d (1.4, can use deepspeed to reduce training memory), it can successfully reproduce the detection results of streampetr. I am currently migrating omnidrive. Omnidrive uses OpenLanev2, but the evaluation of OpenLanev2 has not been migrated to mmdet3d (1.4), so centerline prediction will be canceled in this version.
> 
> Hi, thanks for opening source quickly. Does this repo support the original StreamPETR pipeline for 3D detection, or I must use the official StreamPETR repo? If support, can you give the config file?

You mean mmdet3d 1.0 or mmdet3d 1.4.0?

**Comment by haofuly** [comment]
> > > update: will opensource omnidrive (mmdet1.0) tomorrow. And I fix bugs in mmdet3d (1.4, can use deepspeed to reduce training memory), it can successfully reproduce the detection results of streampetr. I am currently migrating omnidrive. Omnidrive uses OpenLanev2, but the evaluation of OpenLanev2 has not been migrated to mmdet3d (1.4), so centerline prediction will be canceled in this version.
> > 
> > 
> > Hi, thanks for opening source quickly. Does this repo support the original StreamPETR pipeline for 3D detection, or I must use the official StreamPETR repo? If support, can you give the config file?
> 
> You mean mmdet3d 1.0 or mmdet3d 1.4.0?

anyone of these two support pure StreamPETR? which means i can use the StreamPETR checkpoint and get the similar mAP and NDS.

**Comment by exiawsh** [comment]
You need to retrain the model. Because the state_dict has changed.

**Comment by haofuly** [comment]
> You need to retrain the model. Because the state_dict has changed.

Thanks, can i retrain the pure StreamPETR model without LLM in this repo? I find it hard to do because the training scripts and models has been modified largely from its StreamPETR repo's edition.

**Comment by exiawsh** [comment]
set https://github.com/NVlabs/OmniDrive/blob/1912d53e66c3b42dac20021bb93957a01af212bb/projects/configs/OmniDrive/mask_eva_lane_det_vlm.py#L41C5-L41C13
lm_head and map_head to None. Then retrain the model.

**Comment by haofuly** [comment]
Thanks, i will try it.

**Comment by haofuly** [comment]
> set https://github.com/NVlabs/OmniDrive/blob/1912d53e66c3b42dac20021bb93957a01af212bb/projects/configs/OmniDrive/mask_eva_lane_det_vlm.py#L41C5-L41C13 lm_head and map_head to None. Then retrain the model.

I set `lm_head=None, map_head=None`, but i raise error `RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop. ...`.
So I set `find_unused_parameters=True`, but it still not  work.
Can you share your config for training the pure StreamPETR? Thanks a lot.

**Comment by exiawsh** [comment]
add this. https://github.com/NVlabs/OmniDrive/blob/5dbcb3d6d181f175e571d4d456f67aa73125f9c1/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L251
And set out_dims https://github.com/NVlabs/OmniDrive/blob/5dbcb3d6d181f175e571d4d456f67aa73125f9c1/projects/configs/OmniDrive/mask_eva_lane_det_vlm.py#L105 to None.

**Comment by haofuly** [comment]
@exiawsh Thanks and I am on training. Besides, may I ask why there is no `img_roi_head` in OmniDrive, which is used in StreamPETR ?

**Comment by haofuly** [comment]
> @exiawsh Thanks and I am on training. Besides, may I ask why there is no `img_roi_head` in OmniDrive, which is used in StreamPETR ?

_base_ = [
    '../../../mmdetection3d/configs/_base_/datasets/nus-3d.py',
    '../../../mmdetection3d/configs/_base_/default_runtime.py'
]
backbone_norm_cfg = dict(type='LN', requires_grad=True)
plugin=True
plugin_dir='projects/mmdet3d_plugin/'

# If point cloud range is changed, the models should also change their point
# cloud range accordingly
point_cloud_range = [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
voxel_size = [0.2, 0.2, 8]
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
# For nuScenes we usually do 10-class detection
class_names = [
    'car', 'truck', 'construction_vehicle', 'bus', 'trailer', 'barrier',
    'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone'
]

num_gpus = 8
batch_size = 2
num_iters_per_epoch = 28130 // (num_gpus * batch_size)
num_epochs = 24
llm_path = 'ckpts/pretrain_qformer/'

collect_keys=['lidar2img', 'intrinsics', 'extrinsics','timestamp', 'img_timestamp', 'ego_pose', 'ego_pose_inv', 'command', 'can_bus']
input_modality = dict(
    use_lidar=False,
    use_camera=True,
    use_radar=False,
    use_map=False,
    use_external=True)
model = dict(
    type='Petr3D',
    save_path='./results_planning_only/',  #save path for vlm models.
    use_grid_mask=True,
    frozen=False,
    use_lora=False,
    tokenizer=llm_path,
    lm_head=None, # set to None if don't use llm head
    img_backbone=dict(
        type='VoVNetCP', ###use checkpoint to save memory
        spec_name='V-99-eSE',
        norm_eval=True,
        frozen_stages=-1,
        input_ch=3,
        out_features=('stage4','stage5',)),
    map_head=None,
    img_neck=dict(
        type='CPFPN',  ###remove unused parameters 
        in_channels=[768, 1024],
        out_channels=256,
        num_outs=2),
    img_roi_head=dict(
        type='FocalHead',
        num_classes=10,
        in_channels=256,
        loss_cls2d=dict(
            type='QualityFocalLoss',
            use_sigmoid=True,
            beta=2.0,
            loss_weight=2.0),
        loss_centerness=dict(type='GaussianFocalLoss', reduction='mean', loss_weight=1.0),
        loss_bbox2d=dict(type='L1Loss', loss_weight=5.0),
        loss_iou2d=dict(type='GIoULoss', loss_weight=2.0),
        loss_centers2d=dict(type='L1Loss', loss_weight=10.0),
        train_cfg=dict(
        assigner2d=dict(
            type='HungarianAssigner2D',
            cls_cost=dict(type='FocalLossCost', weight=2.),
            reg_cost=dict(type='BBoxL1Cost', weight=5.0, box_format='xywh'),
            iou_cost=dict(type='IoUCost', iou_mode='giou', weight=2.0),
            centers2d_cost=dict(type='BBox3DL1Cost', weight=10.0)))
        ),
    pts_bbox_head=dict(
        type='StreamPETRHead',
        num_classes=10,
        in_channels=256,
        out_dims=None,
        num_query=644,
        with_mask=True,
        memory_len=1024,
        topk_proposals=256,
        num_propagated=256,
        num_extra=256,
        n_control=11, # align with centerline query defination
        match_with_velo=False,
        scalar=10, ##noise groups
        noise_scale = 1.0, 
        dn_weight= 1.0, ##dn loss weight
        split = 0.75, ###positive rate
        code_weights = [2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        transformer=dict(
            type='PETRTemporalTransformer',
                 input_dimension=256,
                 output_dimension=256,
                 num_layers=6,
                 embed_dims=256,
                 num_heads=8,
                 feedforward_dims=2048,
                 dropout=0.1,
                 with_cp=True,
                 flash_attn=False,
            ),
        bbox_coder=dict(
            type='NMSFreeCoder',
            post_center_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0],
            pc_range=point_cloud_range,
            max_num=300,
            voxel_size=voxel_size,
            num_classes=10), 
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=2.0),
        loss_bbox=dict(type='L1Loss', loss_weight=0.25),
        loss_iou=dict(type='GIoULoss', loss_weight=0.0),),
        # model training and testing settings
    train_cfg=dict(pts=dict(
        grid_size=[512, 512, 1],
        voxel_size=voxel_size,
        point_cloud_range=point_cloud_range,
        out_size_factor=4,
        assigner=dict(
            type='HungarianAssigner3D',
            cls_cost=dict(type='FocalLossCost', weight=2.0),
            reg_cost=dict(type='BBox3DL1Cost', weight=0.25),
            iou_cost=dict(type='IoUCost', weight=0.0), # Fake cost. This is just to make it compatible with DETR head. 
            pc_range=point_cloud_range),)
            )
            )


dataset_type = 'CustomNuScenesDataset'
data_root = './data/nuscenes/'

file_client_args = dict(backend='disk')


ida_aug_conf = {
        "resize_lim": (0.37, 0.45),
        "final_dim": (320, 800),
        "bot_pct_lim": (0.0, 0.0),
        "rot_lim": (0.0, 0.0),
        "H": 900,
        "W": 1600,
        "rand_flip": False,
    }

train_pipeline = [
    dict(type='LoadMultiViewImageFromFiles', to_float32=True),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True, with_bbox=True,
        with_label=True, with_bbox_depth=True),
    dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='ObjectNameFilter', classes=class_names),
    dict(type='ResizeCropFlipRotImage', data_aug_conf = ida_aug_conf, training=True),
    dict(type='ResizeMultiview3D', img_scale=(640, 640), keep_ratio=False, multiscale_mode='value'),
    dict(type='GlobalRotScaleTransImage',
            rot_range=[-0.3925, 0.3925],
            translation_std=[0, 0, 0],
            scale_ratio_range=[0.95, 1.05],
            reverse_angle=True,
            training=True,
            ),
    dict(type='LoadAnnoatationVQA', 
         base_vqa_path='./data/nuscenes/vqa/train/', 
         base_desc_path='./data/nuscenes/desc/train/',
         base_conv_path='./data/nuscenes/conv/train/',
         base_key_path='./data/nuscenes/keywords/train/',
         tokenizer=llm_path, 
         max_length=2048, 
         ignore_type=[],
         lane_objs_info="./data/nuscenes/lane_obj_train.pkl"),
    dict(type='NormalizeMultiviewImage', **img_norm_cfg),
    dict(type='PadMultiViewImage', size_divisor=32),
    dict(type='PETRFormatBundle3D', class_names=class_names, collect_keys=collect_keys + ['prev_exists']),
    dict(type='Collect3D', keys=['lane_pts', 'input_ids', 'vlm_labels', 'gt_bboxes_3d', 'gt_labels_3d', 'img', 'gt_bboxes', 'gt_labels', 'centers2d', 'depths', 'prev_exists'] + collect_keys,
             meta_keys=('filename', 'ori_shape', 'img_shape', 'pad_shape', 'scale_factor', 'flip', 'box_mode_3d', 'box_type_3d', 'img_norm_cfg', 'scene_token', 'gt_bboxes_3d','gt_labels_3d'))
]
test_pipeline = [
    dict(type='LoadMultiViewImageFromFiles', to_float32=True),
    dict(type='ResizeCropFlipRotImage', data_aug_conf = ida_aug_conf, training=False),
    dict(type='ResizeMultiview3D', img_scale=(640, 640), keep_ratio=False, multiscale_mode='value'),
    dict(type='NormalizeMultiviewImage', **img_norm_cfg),
    dict(type='PadMultiViewImage', size_divisor=32),
    dict(type='LoadAnnoatationVQATest', 
         base_vqa_path='./data/nuscenes/vqa/val/', 
         base_conv_path='./data/nuscenes/conv/val/',
         base_counter_path='./data/nuscenes/eval_cf/',
         load_type=["planning"], # please don't test all the questions in single test, it requires quite long time
         tokenizer=llm_path, 
         max_length=2048,),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1333, 800),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='PETRFormatBundle3D',
                collect_keys=collect_keys,
                class_names=class_names,
                with_label=False),
            dict(type='Collect3D', keys=['input_ids', 'img'] + collect_keys,
            meta_keys=('sample_idx', 'vlm_labels', 'filename', 'ori_shape', 'img_shape','pad_shape', 'scale_factor', 'flip', 'box_mode_3d', 'box_type_3d', 'img_norm_cfg', 'scene_token'))
        ])
]

data = dict(
    samples_per_gpu=batch_size,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=data_root + 'nuscenes2d_ego_temporal_infos_train.pkl',
        seq_split_num=1, # streaming video training
        seq_mode=True, # streaming video training
        pipeline=train_pipeline,
        classes=class_names,
        modality=input_modality,
        test_mode=False,
        use_valid_flag=True,
        filter_empty_gt=False,
        box_type_3d='LiDAR'),
    val=dict(
        type=dataset_type, 
        eval_mode=['det'],
        pipeline=test_pipeline, 
        ann_file=data_root + 'nuscenes2d_ego_temporal_infos_val.pkl',
        classes=class_names, 
        modality=input_modality),
    test=dict(
        type=dataset_type, 
        eval_mode=['lane', 'det'],
        pipeline=test_pipeline, 
        ann_file=data_root + 'nuscenes2d_ego_temporal_infos_val.pkl', 
        classes=class_names, 
        modality=input_modality),
    shuffler_sampler=dict(
        type='InfiniteGroupEachSampleInBatchSampler',
        seq_split_num=2,
        warmup_split_num=10, # lane det and vlm need short term temporal fusion in the early stage of training
        num_iters_to_seq=num_iters_per_epoch,
    ),
    nonshuffler_sampler=dict(type='DistributedSampler')
    )


optimizer = dict(constructor='LearningRateDecayOptimizerConstructor', type='AdamW', 
                 lr=4e-4, betas=(0.9, 0.999), weight_decay=0.01,
                 paramwise_cfg={'decay_rate': 0.9,
                                'head_decay_rate': 4.0,
                                'lm_head_decay_rate': 0.1,
                                'decay_type': 'vit_wise',
                                'num_layers': 24,
                                'custom_keys':{
                                'img_backbone': dict(lr_mult=0.1), # set to 0.1 always better when apply 2D pretrained.
        }
                                })

optimizer_config = dict(type='Fp16OptimizerHook', loss_scale='dynamic', grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='CosineAnnealing',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    min_lr_ratio=1e-3,
    )

evaluation = dict(interval=num_iters_per_epoch*num_epochs, pipeline=test_pipeline)

find_unused_parameters=False #### when use checkpoint, find_unused_parameters must be False
checkpoint_config = dict(interval=num_iters_per_epoch//2, max_keep_ckpts=3)
runner = dict(
    type='IterBasedRunner', max_iters=num_epochs * num_iters_per_epoch)
load_from='ckpts/fcos3d_vovnet_imgbackbone-remapped.pth'
resume_from=None

**Comment by Baymax1520301** [comment]
> > https://github.com/NVlabs/OmniDrive/blob/1912d53e66c3b42dac20021bb93957a01af212bb/projects/configs/OmniDrive/mask_eva_lane_det_vlm.py#L41C5-L41C13 lm_head 和 map_head 设置为 None。然后重新训练模型。
> 
> 我设置了 ，但我引发了错误。所以我设置了 ，但它仍然不起作用。您能否分享用于训练纯 StreamPETR 的配置？多谢。`lm_head=None, map_head=None``RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the forward function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop. ...``find_unused_parameters=True`

Hi, May I ask how your training results are ?Can you share your config for training the pure StreamPETR?

**Comment by haofuly** [comment]
> 
> Hi, May I ask how your training results are ?Can you share your config for training the pure StreamPETR?

@Baymax1520301 Hi, this result could match with original StreamPETR_vov. For alignment, there are three python file to modify: (1) `./projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py`, the author use extra query as LLM input, which is used in pure StreamPETR; (2) `./projects/mmdet3d_plugin/models/detector/petr3d.py`, the train and test pipeline; (3) imitate the original config to modify the config_file in this repo.

**Comment by Baymax1520301** [comment]
> For alignment, there are three python file to modify: (1) , the author use extra query as LLM input, which is used in pure StreamPETR; (2) , the train and test pipeline; (3) imitate the original config to modify the config_file in this

Thank you very much for your reply. I want to train a pure StreamPETR model because after training OmniDrive, I found that its 3D perception is not good. Is this also the case for you？

**Comment by haofuly** [comment]
> 
> Thank you very much for your reply. I want to train a pure StreamPETR model because after training OmniDrive, I found that its 3D perception is not good. Is this also the case for you？

yes, the detection performance of Omni worse than its pure baseline.

**Comment by Baymax1520301** [comment]
> > 非常感谢您的回复。我想训练一个纯 StreamPETR 模型，因为在训练 OmniDrive 后，我发现它的 3D 感知并不好。您也是这种情况吗？
> 
> 是的，Omni 的检测性能比其纯基线差。

May I ask how your learning rate is set？

**Comment by haofuly** [comment]
> 
> May I ask how your learning rate is set？

I just follow Omni's lr setting for training Omni and StreamPETR's lr for training pure StreamPETR.

**Comment by haofuly** [comment]
> 
> Is it convenient to add WeChat? I think I still have many questions to ask you for advice.

18253808990
