### ISSUE TITLE
How to align vision_embed to other VLM model?

### ISSUE THREAD

**Issue by RobotiX101** [NVlabs/OmniDrive#6]
Great work and thanks for code release. While I still have questions as title suggests. Your paper uses a q-former network to achieve strong alignment between driving tasks and LLAVA agent. But I do not find codes around q-former alignment training. Would you have plan to release code of these part or keep it a pretrained weight?

**Comment by exiawsh** [comment]
We used Llava's data and code for training. Then replace mlp projector with PETR/QFormer. This part of the code is a bit time-consuming to organize, and currently we plan to make it public as pretrain weights. In the future, we will provide more pre-trained weights, such as tiny models like tinyllama and qwen2, and even switch the projector back to MLP.

**Comment by RobotiX101** [comment]
> We used Llava's data and code for training. Then replace mlp projector with PETR/QFormer. This part of the code is a bit time-consuming to organize, and currently we plan to make it public as pretrain weights. In the future, we will provide more pre-trained weights, such as tiny models like tinyllama and qwen2, and even switch the projector back to MLP.

thks
