### ISSUE TITLE
ego_boxes

### ISSUE THREAD

**Issue by Timer-x** [NVlabs/OmniDrive#8]
https://github.com/NVlabs/OmniDrive/blob/1912d53e66c3b42dac20021bb93957a01af212bb/evaluation/eval_planning.py#L30

what's the meaning of "0.5 + 0.985793"

thanks for your reply

**Comment by exiawsh** [comment]
distance between imu (ego coordinate) and vehicle center

**Comment by Timer-x** [comment]
i wonder how to get this information

**Comment by exiawsh** [comment]
I refer to the implementation in BEV-Planner.

**Comment by Timer-x** [comment]
Thanks a lot
